# Server
server.port=${PORT:8080}

# Database
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/finance_db}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=${JWT_SECRET:myLocalSecretKey12345678901234567890}
jwt.expiration=${JWT_EXPIRATION:86400000}